services:
  postgres_database:
    image: postgres:latest  # required "postgres:latest"
    restart: always
    container_name: AlxProDev_postgres
    env_file:
      - .env  # contains POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: AlxProDev_redis
    restart: always
    volumes:
      - redis_data:/data  # required "redis_data"
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
